alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: tomato.olepunchy.dev
  zone: olepunchy.dev
name: tomato
region: nyc
services:
- http_port: 80
  image:
    registry: olepunchy
    registry_type: DOCKER_HUB
    repository: tomato
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  name: tomato
  routes:
  - path: /
  source_dir: /
